# Define stages
stages:
  - build
  - test

check_dependencies:
  stage: build
  image: chedy007/freeciv:1.0  # Use your Docker image
  script:
    - ls
    - echo "Checking dependencies..."
    - ./autogen.sh --no-configure-run

generate_makefiles:
  stage: build
  image: chedy007/freeciv:1.0  # Use your Docker image
  script:
    - echo "generating make files"
    - mkdir build && cd build && ../configure
  artifacts:
    paths:
      - .

build_binaries:
  stage: build
  image: chedy007/freeciv:1.0  # Use your Docker image
  script:
    - echo "Running make..."
    - cd build
    - make
  needs:
    - job: generate_makefiles
      artifacts: true
  artifacts:
    paths:
      - .

test:
  stage: test
  image: chedy007/freeciv:1.0  # Use your Docker image
  script:
    - echo "Running tests..."
    - cd build && make check
  needs:
    - job: build_binaries
      artifacts: true
