# Define stages
stages:
  - build
  - test

check_dependencies:
  stage: build
  image: chedy007/freeciv:1.0  # Use your Docker image
  script:
    - ls
    - echo "Checking dependencies..."
    - mkdir build && cd build && ../autogen.sh
  artifacts:
    paths:
      - build

build_binaries:
  stage: build
  image: chedy007/freeciv:1.0  # Use your Docker image
  script:
    - echo "Running make..."
    - cd build
    - make
  needs:
    - job: check_dependencies
      artifacts:
        paths:
          - build

test:
  stage: test
  image: chedy007/freeciv:1.0  # Use your Docker image
  script:
    - echo "Running tests..."
    - pwd
    - ls | grep build
    - cd build && make check
  needs:
    - job: build_binaries
      artifacts: true
