# Define the stages of the pipeline
stages:
  - build
  - test

# Define a job to install dependencies
install_dependencies:
  stage: build
  image: ubuntu:latest
  script:
    - apt-get update
    - apt-get install -y build-essential autoconf automake libtool pkg-config
    - apt-get install -y libgtk-3-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev
    - apt-get install -y libsdl2-ttf-dev libcurl4-openssl-dev libjson-c-dev
    - apt-get install -y libsqlite3-dev libpq-dev
  artifacts:
    name: "dependencies"
    paths:
      - /usr/include
      - /usr/lib

# Define a job to run autogen.sh
prepare_build_system:
  stage: build
  image: ubuntu:latest
  script:
    - ./autogen.sh
  dependencies:
    - install_dependencies
  artifacts:
    name: "autogen"
    paths:
      - .

# Define a job to configure the build
configure:
  stage: build
  image: ubuntu:latest
  script:
    - mkdir build && cd build
    - ../configure
  dependencies:
    - prepare_build_system
  artifacts:
    name: "configure"
    paths:
      - .

# Define a job to build the project
build:
  stage: build
  image: ubuntu:latest
  script:
    - make -j$(nproc)
  dependencies:
    - configure
  artifacts:
    name: "build"
    paths:
      - .

# Define a job to run tests
test:
  stage: test
  image: ubuntu:latest
  script:
    - make check
  dependencies:
    - build
